import { buildDirectorInstruction, normalizeDirectorState } from './director-copy.js';

// Canvas presentation only.  Keep visual changes here; game state lives in
// session.js and remains server-authoritative.
const T = 20, W = 60, H = 34;
const C = { grass: '#72bd58', ink: '#27324a', gold: '#f7d25c', purple: '#9b75c9' };

export function createRenderer(canvas, session) {
  const ctx = canvas.getContext('2d'); ctx.imageSmoothingEnabled = false;
  const art = {}; let authoredForest = null;
  const { state, mapPoint, relics, activeEntities, abilities, gameReady } = session;
  const image = new Image(); image.src = '/game-art/camping-32.png'; image.addEventListener('load', () => { art.camping = image; render(); });
  const dungeonTiles = new Image(); dungeonTiles.src = '/game-art/dungeon/Dungeon_Tileset.png'; dungeonTiles.addEventListener('load', () => { art.dungeon = dungeonTiles; render(); });
  const dungeonChest = new Image(); dungeonChest.src = '/game-art/dungeon/chest_1.png'; dungeonChest.addEventListener('load', () => { art.dungeonChest = dungeonChest; render(); });
  const dungeonSeal = new Image(); dungeonSeal.src = '/game-art/dungeon/coin_1.png'; dungeonSeal.addEventListener('load', () => { art.dungeonSeal = dungeonSeal; render(); });
  const dungeonCharacters = new Image(); dungeonCharacters.src = '/game-art/dungeon/Dungeon_Character.png'; dungeonCharacters.addEventListener('load', () => { art.dungeonCharacters = dungeonCharacters; render(); });
  for (const [key, file] of Object.entries({ shadowBackground:'forest-background.avif', shadowTerrain:'terrain.png', shadowIdle:'idle.png', shadowRun:'run.png', shadowJump:'jump.png', shadowFall:'fall.png', shadowExit:'exit.png' })) { const sprite = new Image(); sprite.src = `/game-art/shadow-forest/${file}`; sprite.addEventListener('load', () => { art[key] = sprite; render(); }); }
  for (const [key, file] of Object.entries({ trapSpikes:'spikes.png', trapTrampoline:'trampoline-idle.png', trapFan:'fan.png', trapFire:'fire.png', trapSaw:'saw.png' })) { const sprite = new Image(); sprite.src = `/game-art/shadow-forest/traps/${file}`; sprite.addEventListener('load', () => { art[key] = sprite; render(); }); }
  for (const [key, file] of Object.entries({ moonBackground:'background.png', moonShrine:'shrine.png' })) { const sprite = new Image(); sprite.src = `/game-art/moon-shrine/${file}`; sprite.addEventListener('load', () => { art[key] = sprite; render(); }); }
  for (const [key, file] of Object.entries({ ghostBackground:'background.png', ghostSprite:'ghost.png', ghostShard:'shard.png' })) { const sprite = new Image(); sprite.src = `/game-art/ghost-village/${file}`; sprite.addEventListener('load', () => { art[key] = sprite; render(); }); }
  for (const id of [1, 2, 3, 5]) { const sprite = new Image(); sprite.src = `/game-art/retro-characters/player-${id}.png`; sprite.addEventListener('load', () => { art[`player${id}`] = sprite; render(); }); }
  fetch('/game-art/forest.json').then((response) => response.ok ? response.json() : null).then((layout) => { authoredForest = layout; render(); }).catch(() => {});

  function px(x) { const shake=state.hurtTimer>0?(Math.floor(state.frame*8)%2?1:-1)*3*state.hurtStrength:0; return Math.floor(x * T - (state.camera.x * T - canvas.width / 2) + shake); }
  function py(y) { const shake=state.hurtTimer>0?(Math.floor(state.frame*8)%2?-1:1)*2*state.hurtStrength:0; return Math.floor(y * T - (state.camera.y * T - canvas.height / 2) + shake); }
  function panel(x, y, w, h) { ctx.fillStyle = 'rgba(29,47,68,.9)'; ctx.fillRect(x, y, w, h); ctx.strokeStyle = '#f5dd8a'; ctx.lineWidth = 2; ctx.strokeRect(x + 1, y + 1, w - 2, h - 2); }
  function sheetTile(gid, X, Y) { const tile = gid - 1, columns = Math.floor(art.camping.width / 32); ctx.drawImage(art.camping, (tile % columns) * 32, Math.floor(tile / columns) * 32, 32, 32, X, Y, T, T); }
  function drawTile(x, y) { const X = px(x), Y = py(y), index = y * W + x; if (!authoredForest || !art.camping || x < 0 || y < 0 || x >= W || y >= H) { ctx.fillStyle = C.grass; ctx.fillRect(X, Y, T, T); return; } for (const layer of authoredForest.layers || []) { const gid = layer.data?.[index] || 0; if (gid) sheetTile(gid, X, Y); } }
  function drawTerrain(area) { const point = mapPoint(area), width = Math.max(1, Number(area.w) || 1) * T, height = Math.max(1, Number(area.h) || 1) * T, kind = String(area.kind || '').toLowerCase(); if (kind.includes('water')) { ctx.fillStyle = 'rgba(57,161,211,.72)'; ctx.fillRect(px(point.x), py(point.y), width, height); } else if (kind.includes('bridge')) { ctx.fillStyle = '#7d5536'; ctx.fillRect(px(point.x), py(point.y) + 6, width, Math.max(7, height - 10)); } else if (kind.includes('spirit')) { ctx.fillStyle = 'rgba(123,80,175,.42)'; ctx.fillRect(px(point.x), py(point.y), width, height); } else { ctx.fillStyle = 'rgba(208,194,112,.58)'; ctx.fillRect(px(point.x), py(point.y), width, height); } }
  function dungeonWall(x, y) { return x < 1 || x > 18 || y < 1 || y > 14 || (x === 9 && y >= 2 && y <= 6 && y !== 4) || (y === 8 && x >= 3 && x <= 16 && ![7, 10, 14].includes(x)); }
  function drawDungeonTile(x, y) { const X = px(x), Y = py(y), wall = dungeonWall(x, y); ctx.fillStyle = wall ? '#231b2d' : '#35243e'; ctx.fillRect(X, Y, T, T); if (art.dungeon) ctx.drawImage(art.dungeon, wall ? 16 : 32, wall ? 0 : 32, 16, 16, X, Y, T, T); }
  const shadowPlatforms=[{x:0,y:12,w:5},{x:6,y:11,w:4},{x:11,y:12,w:3},{x:15,y:10,w:3},{x:19,y:12,w:6},{x:3,y:8,w:4},{x:8,y:7,w:3},{x:12,y:5,w:4},{x:17,y:7,w:3},{x:21,y:5,w:3}];
  const shadowTraps=[{x:7.35,y:11,w:1.1},{x:19.65,y:12,w:1.1}],shadowFire=[{x:16.1,y:10,w:1},{x:21.1,y:12,w:.9}],shadowTrampoline={x:3.15,y:12,w:1},shadowFan={x:12.6,y:12,w:1.1,top:5.2};
  function drawShadowForest(){
    ctx.fillStyle='#123c46';ctx.fillRect(0,0,canvas.width,canvas.height);if(art.shadowBackground){const scale=Math.max(canvas.width/art.shadowBackground.width,canvas.height/art.shadowBackground.height),w=art.shadowBackground.width*scale,h=art.shadowBackground.height*scale;ctx.drawImage(art.shadowBackground,(canvas.width-w)/2,(canvas.height-h)/2,w,h);}
    shadowPlatforms.forEach((p)=>{for(let x=p.x;x<p.x+p.w;x++){const X=px(x),Y=py(p.y);ctx.fillStyle='#6e4736';ctx.fillRect(X,Y,T,T);if(art.shadowTerrain)ctx.drawImage(art.shadowTerrain,96,0,16,16,X,Y,T,T);}});
    shadowTraps.forEach((item)=>{const X=px(item.x),Y=py(item.y);if(art.trapSpikes)ctx.drawImage(art.trapSpikes,0,0,16,16,X,Y-16,item.w*T,20);});
    shadowFire.forEach((item,index)=>{const X=px(item.x),Y=py(item.y),frame=Math.floor(state.frame*1.5+index)%3;if(art.trapFire)ctx.drawImage(art.trapFire,frame*16,0,16,32,X,Y-28,item.w*T,32);});
    let X=px(shadowTrampoline.x),Y=py(shadowTrampoline.y);if(art.trapTrampoline)ctx.drawImage(art.trapTrampoline,0,0,28,28,X,Y-14,shadowTrampoline.w*T,20);
    X=px(shadowFan.x);Y=py(shadowFan.y);if(art.trapFan){const frame=Math.floor(state.frame*2)%4;ctx.drawImage(art.trapFan,frame*24,0,24,8,X,Y-10,shadowFan.w*T,10);}ctx.strokeStyle='rgba(210,245,255,.55)';for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(X+i*5,Y-14);ctx.lineTo(X+i*5+Math.sin(state.frame*.8+i)*4,py(shadowFan.top));ctx.stroke();}
    const sawTime=state.mine?.shadowForest?.sawTime||0,sawX=8.15+(Math.sin(sawTime*2.4)+1)*1.05,sx=px(sawX),sy=py(5.8);if(art.trapSaw){const frame=Math.floor(state.frame*2)%8;ctx.drawImage(art.trapSaw,frame*38,0,38,38,sx-9,sy-9,38,38);}
    X=px(22.15);Y=py(2.7);ctx.fillStyle='rgba(220,255,238,.28)';ctx.fillRect(X-4,Y-4,48,55);if(art.shadowExit)ctx.drawImage(art.shadowExit,0,0,64,64,X,Y,40,40);
  }
  function drawMoonShrine(){ctx.fillStyle='#0d1428';ctx.fillRect(0,0,canvas.width,canvas.height);if(art.moonBackground)ctx.drawImage(art.moonBackground,0,0,canvas.width,canvas.height);const mission=state.mine?.moonShrine||{},path=[{x:2,y:10},{x:7,y:10},{x:7,y:7},{x:13,y:7},{x:13,y:10},{x:19,y:10},{x:19,y:6},{x:24,y:6},{x:28,y:5}],ready=Number(mission.pathStep||0)>=path.length-1;ctx.strokeStyle=mission.lineFailed?'#b73f58':'rgba(222,248,255,.9)';ctx.lineWidth=7;ctx.lineCap='round';ctx.lineJoin='round';ctx.shadowColor=mission.lineFailed?'#7d1f38':'#a8e8ff';ctx.shadowBlur=12;ctx.beginPath();path.forEach((point,index)=>index?ctx.lineTo(px(point.x)+10,py(point.y)+10):ctx.moveTo(px(point.x)+10,py(point.y)+10));ctx.stroke();ctx.shadowBlur=0;path.forEach((point,index)=>{ctx.fillStyle=index<=Number(mission.pathStep||0)?'#effcff':'#53637b';ctx.beginPath();ctx.arc(px(point.x)+10,py(point.y)+10,6,0,Math.PI*2);ctx.fill();});if(ready){const X=px(28)+10,Y=py(5)+10,pulse=30+Math.sin(state.frame)*6;const glow=ctx.createRadialGradient(X,Y,4,X,Y,pulse);glow.addColorStop(0,'rgba(235,252,255,.95)');glow.addColorStop(1,'rgba(140,215,255,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(X,Y,pulse,0,Math.PI*2);ctx.fill();ctx.shadowColor='#dff8ff';ctx.shadowBlur=22;}if(art.moonShrine)ctx.drawImage(art.moonShrine,0,0,112,224,px(27),py(1),40,80);ctx.shadowBlur=0;}
  function drawEntity(entity) { const X = px(entity.x), Y = py(entity.y), kind = String(entity.kind || entity.type || '').toLowerCase(); if (kind.includes('dungeon-enemy')) { const sprite=Number(entity.sprite)||0,sx=(sprite%7)*16,sy=Math.floor(sprite/7)*16;if(art.dungeonCharacters)ctx.drawImage(art.dungeonCharacters,sx,sy,16,16,X,Y,20,20);if(state.attackTimer>0&&state.attackTargetId===entity.id){ctx.fillStyle=`rgba(255,245,210,${Math.min(1,state.attackTimer*3)})`;ctx.fillRect(X+2,Y+2,16,16);}ctx.fillStyle='#35151f';ctx.fillRect(X+2,Y-4,16,3);ctx.fillStyle='#e45b69';ctx.fillRect(X+2,Y-4,Math.round(16*(entity.hp/3)),3); } else if (kind.includes('dungeon-sigil')) { if (art.dungeonSeal) ctx.drawImage(art.dungeonSeal, X + 2, Y + 2, 16, 16); else { ctx.fillStyle='#8ce8ff';ctx.fillRect(X+6,Y+4,8,12); } } else if (kind.includes('dungeon-altar')) { if (art.dungeonChest) ctx.drawImage(art.dungeonChest, X + 2, Y + 2, 16, 16); ctx.strokeStyle=entity.active?'#8ce8ff':'#775b85';ctx.strokeRect(X,Y,20,20); } else if (kind.includes('dungeon-exit')) { ctx.fillStyle=entity.active?'#76d9ee':'#433650';ctx.fillRect(X+3,Y+2,14,17);ctx.fillStyle='#171322';ctx.fillRect(X+7,Y+6,6,13); } else if (kind.includes('finale-circle')) { ctx.strokeStyle = entity.role === state.mine?.archetype ? '#fff2a8' : '#9ed7c0'; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(X + 10, Y + 10, 9, 0, Math.PI * 2); ctx.stroke(); ctx.fillStyle = 'rgba(166,232,198,.28)'; ctx.fillRect(X + 5, Y + 5, 10, 10); } else if (kind.includes('finale-destination')) { ctx.fillStyle = entity.transformed ? '#ecfcb7' : '#bd9f65'; ctx.fillRect(X, Y + 5, 20, 15); ctx.fillStyle = entity.transformed ? '#75e6bd' : '#625877'; ctx.fillRect(X + 6, Y, 8, 15); } else if (kind.includes('relic')) { ctx.fillStyle = C.gold; ctx.fillRect(X + 6, Y + 4, 8, 12); ctx.fillStyle = '#fff4b5'; ctx.fillRect(X + 8, Y + 2, 4, 5); } else if (kind === 'world-evolution') { ctx.fillStyle = entity.dormant ? '#4b514b' : '#c9b875'; ctx.fillRect(X + 1, Y + 7, 18, 11); ctx.fillStyle = entity.dormant ? '#303934' : '#8ce1b0'; ctx.fillRect(X + 5, Y + 3, 10, 11); ctx.fillStyle = entity.dormant ? '#726b5d' : '#e9ffd1'; ctx.fillRect(X + 8, Y + 1, 4, 5); if (!entity.dormant) { ctx.strokeStyle = 'rgba(190,255,205,.55)'; ctx.strokeRect(X - 2, Y - 2, 24, 24); } } else if (kind.includes('gate') || kind.includes('spirit')) { ctx.fillStyle = '#4f376f'; ctx.fillRect(X + 3, Y + 2, 14, 16); ctx.fillStyle = '#d9b4ff'; ctx.fillRect(X + 6, Y + 5, 8, 11); } else if (kind.includes('shrine')) { ctx.fillStyle = '#d8d4bd'; ctx.fillRect(X + 3, Y + 7, 14, 10); ctx.fillStyle = C.purple; ctx.fillRect(X + 7, Y + 1, 6, 9); } else if (kind.includes('temple') || kind.includes('altar')) { ctx.fillStyle = '#b9a882'; ctx.fillRect(X, Y + 5, 20, 15); ctx.fillStyle = kind.includes('altar') ? C.gold : '#706879'; ctx.fillRect(X + 7, Y + 8, 6, 12); } else { ctx.fillStyle = '#d8d4bd'; ctx.fillRect(X + 4, Y + 4, 12, 12); } }
  function drawGhostVillage(){ctx.fillStyle='#100c1d';ctx.fillRect(0,0,canvas.width,canvas.height);if(art.ghostBackground)ctx.drawImage(art.ghostBackground,0,50,canvas.width,540);const player=state.mine,mission=player?.ghostVillage;if(!mission)return;mission.ghosts.filter((ghost)=>ghost.active).forEach((ghost)=>{const X=px(ghost.x),Y=py(ghost.z),bob=Math.sin(state.frame+ghost.x)*4;ctx.fillStyle='rgba(175,225,255,.18)';ctx.beginPath();ctx.arc(X+10,Y+10+bob,18,0,Math.PI*2);ctx.fill();if(art.ghostSprite)ctx.drawImage(art.ghostSprite,X-2,Y-2+bob,24,24);});for(const shot of mission.projectiles||[]){const X=px(shot.x),Y=py(shot.z);ctx.fillStyle='rgba(190,240,255,.35)';ctx.beginPath();ctx.arc(X+8,Y+8,12,0,Math.PI*2);ctx.fill();if(art.ghostShard)ctx.drawImage(art.ghostShard,X,Y,16,16);}const aim=state.aimScreen,aimX=(aim.x+(state.camera.x*T-canvas.width/2))/T,aimZ=(aim.y+(state.camera.y*T-canvas.height/2))/T,dx=aimX-player.x,dz=aimZ-(player.y-.4),length=Math.max(.2,Math.hypot(dx,dz)),vx=dx/length*10,vz=dz/length*10;ctx.fillStyle='rgba(225,250,255,.75)';for(let t=.12;t<2.1;t+=.16){const x=player.x+vx*t,z=player.y-.4+vz*t+3.5*t*t;if(z>12.5||x<0||x>28)break;ctx.beginPath();ctx.arc(px(x)+8,py(z)+8,3,0,Math.PI*2);ctx.fill();}panel(315,14,330,58);ctx.textAlign='center';ctx.font='bold 11px monospace';ctx.fillStyle='#dff8ff';ctx.fillText(`GHOSTS CAUGHT · ${mission.caught}/6`,480,36);ctx.font='10px monospace';ctx.fillText('RUN A/D · AIM ARC WITH MOUSE · CLICK TO THROW',480,56);}
  function character(player) { if(player.realm==='moon-shrine')drawMoonShrine();if(player.realm==='ghost-village')drawGhostVillage();const X = px(player.x), Y = py(player.y);if(player.realm==='shadow-forest'){const mission=player.shadowForest||{},sprite=art[`player${player.sprite}`],moving=Math.abs(mission.vx||0)>.1,frame=moving?Math.floor(state.frame*1.4)%3:1,row=(mission.vx||0)<0?1:2;if(sprite)ctx.drawImage(sprite,frame*32,row*32,32,32,X-12,Y-19,44,44);else{ctx.fillStyle='#67d9ec';ctx.fillRect(X,Y+2,20,26);}return;}const sprite=art[`player${player.sprite}`], rows={down:0,left:1,right:2,up:3}, row=rows[player.facing]??0, frame=player.moving?Math.floor(state.frame*1.4)%3:1;if(player.realm==='moon-shrine'){if(sprite)ctx.drawImage(sprite,frame*32,row*32,32,32,X-12,Y-19,44,44);else{ctx.fillStyle=player.color;ctx.fillRect(X,Y,20,26);}return;} if(sprite)ctx.drawImage(sprite,frame*32,row*32,32,32,X-6,Y-10,32,32);else{ctx.fillStyle=C.ink;ctx.fillRect(X+4,Y+4,10,11);ctx.fillStyle=player.color;ctx.fillRect(X+5,Y+5,8,8);}ctx.fillStyle=player.color;ctx.fillRect(X+3,Y+18,14,2);if(player===state.mine&&state.hurtTimer>0&&Math.floor(state.frame*12)%2===0){ctx.fillStyle='rgba(255,240,230,.75)';ctx.fillRect(X-4,Y-8,28,28);} }
  function drawAttack() { const player=state.mine;if(!player||state.attackTimer<=0||player.realm!=='dungeon')return;const X=px(player.x)+10,Y=py(player.y)+10,dx=state.attackTargetX-player.x,dy=state.attackTargetY-player.y,angle=Math.atan2(dy,dx),progress=1-state.attackTimer/.28,swing=angle-.9+progress*1.8;ctx.save();ctx.translate(X,Y);ctx.rotate(swing);ctx.fillStyle='#d9e7ee';ctx.fillRect(8,-2,15,4);ctx.fillStyle='#fff8c9';ctx.fillRect(20,-1,7,2);ctx.fillStyle='#8b6b46';ctx.fillRect(4,-3,6,6);ctx.restore(); }
  function label(text, x, y, color = '#fff7d5') { ctx.font = 'bold 10px monospace'; ctx.textAlign = 'center'; ctx.fillStyle = C.ink; ctx.fillText(text, px(x) + 1, py(y) - 6); ctx.fillStyle = color; ctx.fillText(text, px(x), py(y) - 7); }
  function wrap(text, x, y, max, line) { const words = String(text || '').split(' '); let current = '', yy = y; for (const word of words) { if (ctx.measureText(`${current}${word}`).width > max) { ctx.fillText(current, x, yy); current = `${word} `; yy += line; } else current += `${word} `; } ctx.fillText(current, x, yy); }
  function drawDirectorHud() {
    const { directives } = normalizeDirectorState(state.world, state.network.playerId);
    if (!directives.length) return;
    const instruction = buildDirectorInstruction(state.world, state.network.playerId);
    panel(14, 214, 365, 56); ctx.textAlign = 'left'; ctx.font = 'bold 10px monospace'; ctx.fillStyle = '#9de3ff'; ctx.fillText('THE GAME MASTER SHIFTS THE WORLD', 27, 234); ctx.fillStyle = '#fff7d5'; ctx.font = '10px monospace'; wrap(instruction, 27, 251, 335, 12);
  }
  function drawHud() { const mine = state.mine; panel(14, 14, 306, 62); ctx.textAlign = 'left'; ctx.font = 'bold 13px monospace'; ctx.fillStyle = '#fff2bd'; ctx.fillText('EVERDAWN', 27, 35); ctx.font = '11px monospace'; ctx.fillStyle = '#d2f0cf'; ctx.fillText(!state.network.connected ? 'CONNECTING TO THE WORLD…' : !gameReady() ? `GATHERING LANTERNS · ${state.players.length}/4` : state.world?.phase === 'observing' ? `THE GM OBSERVES · ${state.world.observationSecondsRemaining ?? '?'}s` : `YOUR ROLE · ${mine?.archetype || 'awakening'}`, 27, 55); panel(600, 14, 148, 43); ctx.font = '10px monospace'; ctx.fillStyle = '#fff7d5'; ctx.fillText('MOVE  WASD / ARROWS', 613, 33); ctx.fillText('INTERACT  E  ·  FULLSCREEN  F', 613, 48); panel(760, 14, 186, 104); ctx.font = 'bold 10px monospace'; ctx.fillStyle = '#fff2bd'; ctx.fillText(`LANTERNS · ${state.network.roomCode || '—'}`, 774, 34); state.players.forEach((player, index) => { ctx.fillStyle = player.color; ctx.fillRect(775, 43 + index * 15, 7, 7); ctx.fillStyle = '#fff'; ctx.fillText(`${player.name} · ${player.archetype || 'observed'}`, 788, 50 + index * 15); }); const target = mine && relics().filter((r) => !r.collectedBy).map((r) => ({ relic: r, ...mapPoint(r) })).sort((a, b) => Math.hypot(mine.x - a.x, mine.y - a.y) - Math.hypot(mine.x - b.x, mine.y - b.y))[0]; if (target) { panel(325, 14, 265, 43); ctx.fillText(`RELIC SIGNAL ${target.relic.id.replaceAll('-', ' ')}`, 338, 40); } if (mine?.archetype || abilities().length) { panel(14, 88, 365, 50); ctx.fillStyle = '#f4c7ff'; ctx.fillText(`ROLE · ${mine?.archetype || 'UNREAD'}`, 27, 108); ctx.fillStyle = '#fff7d5'; wrap(abilities().slice(0, 4).join(' · '), 27, 125, 335, 12); } if (state.privateRule) { panel(14, 146, 365, 58); ctx.fillStyle = '#f4c7ff'; ctx.fillText('A LAW ONLY YOU CAN HEAR', 27, 166); ctx.fillStyle = '#fff7d5'; wrap(state.privateRule.message || state.privateRule.title, 27, 184, 335, 12); } if (state.noticeTimer > 0 || !gameReady()) { panel(165, 548, 630, 66); ctx.textAlign = 'center'; ctx.font = 'bold 12px monospace'; ctx.fillStyle = '#fff7d5'; wrap(state.notice, 480, 573, 570, 16); } }
  function drawStart() { ctx.fillStyle = '#70b957'; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.textAlign = 'center'; ctx.font = 'bold 54px monospace'; ctx.fillStyle = C.ink; ctx.fillText('EVERDAWN', 482, 179); ctx.fillStyle = '#fff3b8'; ctx.fillText('EVERDAWN', 480, 175); ctx.font = 'bold 15px monospace'; ctx.fillStyle = '#fff9de'; ctx.fillText('A four-player living tale.', 480, 215); panel(245, 264, 470, 128); ctx.font = 'bold 13px monospace'; ctx.fillStyle = '#f8de90'; ctx.fillText('THE WORLD OPENS ONLY FOR FOUR.', 480, 296); ctx.font = '11px monospace'; ctx.fillStyle = '#e4f1dc'; ctx.fillText('Each wanderer receives a distinct role and a unique ability.', 480, 328); ctx.fillText('CLICK TO LIGHT A LANTERN', 480, 445); }
  function drawLobby() { ctx.fillStyle = 'rgba(20,42,57,.74)'; ctx.fillRect(0, 0, canvas.width, canvas.height); panel(212, 214, 536, 188); ctx.textAlign = 'center'; ctx.font = 'bold 22px monospace'; ctx.fillStyle = '#fff2bd'; ctx.fillText('GATHERING THE EXPEDITION', 480, 255); ctx.font = 'bold 44px monospace'; ctx.fillStyle = '#fff7d5'; ctx.fillText(`${state.players.length} / 4`, 480, 315); ctx.font = '12px monospace'; ctx.fillStyle = '#d2f0cf'; ctx.fillText('The game begins exactly when four lanterns are present.', 480, 347); }
  function drawReflection() { const finale = state.world?.finalObjective, reflection = finale?.reflection; if (!reflection || finale.phase !== 'COMPLETE') return; ctx.fillStyle = 'rgba(14,28,39,.88)'; ctx.fillRect(0, 0, canvas.width, canvas.height); panel(105, 65, 750, 510); ctx.textAlign = 'left'; ctx.fillStyle = '#f7d25c'; ctx.font = 'bold 18px monospace'; ctx.fillText('THE WORLD REMEMBERS', 135, 102); ctx.font = '11px monospace'; ctx.fillStyle = '#fff7d5'; reflection.lines.forEach((line, index) => wrap(line, 135, 138 + index * 28, 690, 14)); ctx.fillStyle = '#9de3ff'; ctx.fillText(`DESTINATION · ${finale.destination.title}`, 135, 310); ctx.fillText(`COMPLICATION · ${finale.complication.title}`, 135, 334); ctx.fillStyle = '#d2f0cf'; ctx.fillText(`ROLES · ${reflection.assignedRoles.map((item) => `${item.name}: ${item.archetype}`).join(' · ')}`, 135, 372); wrap(`EVOLVED WORLD · ${reflection.worldEvolutions.map((item) => item.title).join(' · ')}`, 135, 410, 690, 16); ctx.fillStyle = '#f4c7ff'; ctx.font = 'bold 14px monospace'; ctx.fillText('SO I CREATED THIS WORLD.', 135, 520); }
  function drawDungeonHud() { const mission=state.mine?.dungeon;if(!mission?.active)return;panel(315,14,330,72);ctx.textAlign='center';ctx.font='bold 11px monospace';ctx.fillStyle='#9de3ff';ctx.fillText('BEYOND THE VEIL',480,33);ctx.fillStyle='#fff7d5';const text=mission.phase==='DEFEAT_WARDENS'?`DEFEAT THE THREE WARDENS · ${mission.defeatedCount}/3`:mission.phase==='FIND_SIGILS'?`RECOVER THE THREE SEALS · ${mission.collected.length}/3`:mission.phase==='AWAKEN_ALTAR'?'AWAKEN THE VEIL ALTAR':'RETURN TO THE BLUE PORTAL';ctx.fillText(text,480,52);ctx.fillStyle='#371b29';ctx.fillRect(385,65,190,8);ctx.fillStyle='#e96370';ctx.fillRect(385,65,190*(mission.health/mission.maxHealth),8);ctx.strokeStyle='#fff0d0';ctx.strokeRect(384,64,192,10); }
  function drawShadowHud(){if(!state.mine?.shadowForest?.active)return;panel(285,14,390,62);ctx.textAlign='center';ctx.font='bold 11px monospace';ctx.fillStyle='#a6f5c9';ctx.fillText('THE SHADOW FOREST',480,34);ctx.fillStyle='#fff7d5';ctx.fillText('REACH THE TROPHY - PRESS E TO CLAIM IT',480,55);if(state.mine.x>=22.4&&state.mine.y<6.3){panel(375,92,210,38);ctx.fillStyle='#fff2a8';ctx.fillText('PRESS E AT THE TROPHY',480,116);}}
  function drawHurtEffect() { if(state.hurtTimer<=0||state.mine?.realm!=='dungeon')return;const alpha=Math.min(.34,state.hurtTimer*.7);ctx.fillStyle=`rgba(190,25,48,${alpha})`;ctx.fillRect(0,0,canvas.width,12*state.hurtStrength);ctx.fillRect(0,canvas.height-12*state.hurtStrength,canvas.width,12*state.hurtStrength);ctx.fillRect(0,0,12*state.hurtStrength,canvas.height);ctx.fillRect(canvas.width-12*state.hurtStrength,0,12*state.hurtStrength,canvas.height); }
  function render() { ctx.clearRect(0, 0, canvas.width, canvas.height); if (!state.joined) { drawStart(); return; } const dungeon=state.mine?.realm==='dungeon',shadow=state.mine?.realm==='shadow-forest'; const minX=Math.floor(state.camera.x-25),maxX=Math.ceil(state.camera.x+25),minY=Math.floor(state.camera.y-17),maxY=Math.ceil(state.camera.y+17); if(shadow)drawShadowForest();else if(dungeon){ctx.fillStyle='#120f19';ctx.fillRect(0,0,canvas.width,canvas.height);for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++)drawDungeonTile(x,y);}else{for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++)drawTile(x,y);(state.world?.terrain||[]).forEach(drawTerrain);} const mood=state.world?.director?.mood||state.world?.directorRules?.activeRules?.find((rule)=>rule.card==='world_mood')?.moodId;if(!dungeon&&!shadow&&mood==='mist'){ctx.fillStyle='rgba(220,236,242,.18)';ctx.fillRect(0,0,canvas.width,canvas.height);}if(!dungeon&&!shadow&&mood==='storm'){ctx.fillStyle='rgba(54,67,105,.18)';ctx.fillRect(0,0,canvas.width,canvas.height);}if(!dungeon&&!shadow&&mood==='starlight'){ctx.fillStyle='rgba(82,57,132,.16)';ctx.fillRect(0,0,canvas.width,canvas.height);}if(!shadow)activeEntities().filter((entity)=>dungeon?String(entity.kind).startsWith('dungeon-'):!String(entity.kind).startsWith('dungeon-')).forEach(drawEntity);const visiblePlayers=state.players.filter((player)=>(player.realm||'overworld')===(state.mine?.realm||'overworld'));visiblePlayers.forEach(character);drawAttack();if(!shadow)visiblePlayers.forEach((player)=>label(player.name,player.x,player.y,player.color));drawHurtEffect();drawHud();if(!shadow)drawDirectorHud();if(dungeon)drawDungeonHud();if(shadow)drawShadowHud();if(!gameReady())drawLobby();drawReflection(); }
  return { render };
}
